---
apiVersion: v1
kind: Pod
metadata:
  name: service-kill
  labels:
    app: service-kill
    name: service-kill  
spec:
  nodeName: 
  restartPolicy: Never
  containers:
  - name: service-kill
    image: ubuntu:16.04
    command: ["/bin/bash"]
    args: ["-c", "sleep 10 && systemctl stop docker && sleep 100 && systemctl start kubelet"]
    resources:
      requests:
        cpu: 10m
        memory: 5M
      limits:
        cpu: 100m
        memory: 20M
    volumeMounts:
      - name: bus
        mountPath: /var/run
      - name: root
        mountPath: /node
    securityContext:
      privileged: true
    tty: true
  volumes:
    - name: bus
      hostPath:
        path: /var/run
    - name: root
      hostPath:
        path: /
        type: ""
